### PR TITLE
Response edits 

### PR DESCRIPTION
**Pull request by brianamarie**
@hectorsector What a cool course! ⭐️ I made some edits to responses as I was working my way through. I'll open issues for some bigger picture things, but these should be pretty easy wins.

### CODE REVIEW

**Comment by hectorsector** [comment]
Thanks, @brianamarie! If it's alright with you, I'm going to link to the docs whenever possible on this branch. It may mean cutting some words out but I'm hopeful that using a single source of truth (the docs) for long-form explanations will make maintenance a little easier.

**Comment by hectorsector** [comment]
> I do have some concern about making the posts in the course only instruction. I think a few sentences explaining each concept still have a place in the responses. Are we on the same page?

👍 I'm not planning to remove all explanation. My primary goal is to link to docs when a doc exists. My secondary goal is to remove words when I feel the docs do a good enough job on their own.

**Comment by brianamarie** [comment]
@hectorsector I think I'm 100% behind the primary goal.

For the secondary goal, as a frequent link-clicker and goer-down-of-rabbit-holes, I'm always looking to help users stay on only one page to get the necessary information. For other courses, my understanding is that we'd expect that the user can get all of the information they need for a concept within the explanation, and the docs can provide _additional_ information.  

Going through the course the first time, I felt that wasn't possible, so I added some explanations. As long as you're pruning in small ways I think I'll be on board, but if there are major chops involved I may want to discuss further.

**Comment by hectorsector** [comment]
I hear ya, @brianamarie. Let me make some atomic commits and we can revert liberally.

**Comment by hectorsector** [comment]
Sorry, I didn't mean to merge this. Continued in #12

**Pull request merged**
